# Generated by Django 3.2.7 on 2021-12-22 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='country',
        ),
    ]
